USE scrapy;
alter table lianjia_house change column id id varchar(32) comment '链家编号';
alter table lianjia_house change column layout layout varchar(256) NOT NULL COMMENT '户型';
alter table lianjia_house change column floor floor varchar(128) NOT NULL COMMENT '楼层';
alter table lianjia_house change column total_area total_area varchar(256) NOT NULL DEFAULT '' COMMENT '建筑面积';
alter table lianjia_house change column layout_structure layout_structure varchar(256) NOT NULL DEFAULT '' COMMENT '复式、平层';
alter table lianjia_house change column usable_area usable_area varchar(256) NOT NULL DEFAULT '' COMMENT '套内面积';
alter table lianjia_house change column build_type build_type varchar(32) NOT NULL DEFAULT '' COMMENT '塔楼';
alter table lianjia_house change column orientation orientation varchar(32) NOT NULL DEFAULT '' COMMENT '朝向';
alter table lianjia_house change column construction_year construction_year year NOT NULL DEFAULT '0000' COMMENT '建筑年代';
alter table lianjia_house change column decoration decoration varchar(32) NOT NULL DEFAULT '' COMMENT '精装';
alter table lianjia_house change column build_structure build_structure varchar(64) NOT NULL DEFAULT '' COMMENT '砖混、钢混';
alter table lianjia_house change column heating_mode heating_mode varchar(64) NOT NULL DEFAULT '' COMMENT '供热模式';
alter table lianjia_house change column hshold_ladder_ratio hshold_ladder_ratio varchar(128) NOT NULL DEFAULT '' COMMENT '梯户比';
alter table lianjia_house change column property_right_length property_right_length varchar(64) NOT NULL DEFAULT '' COMMENT '产权年限';
alter table lianjia_house change column elevator elevator varchar(16) NOT NULL DEFAULT '' COMMENT '有无电梯';
alter table lianjia_house change column water_type water_type varchar(16) NOT NULL DEFAULT '' COMMENT '用水类型';
alter table lianjia_house change column electric_type electric_type varchar(16) NOT NULL DEFAULT '' COMMENT '用电类型';
alter table lianjia_house change column gas_price gas_price varchar(16) NOT NULL DEFAULT '' COMMENT '燃气价格';
alter table lianjia_house change column trans_right trans_right varchar(64) NOT NULL DEFAULT '' COMMENT '商品房，经济适用房';
alter table lianjia_house change column house_property house_property varchar(256) NOT NULL DEFAULT '' COMMENT '公寓';
alter table lianjia_house change column ownership_type ownership_type varchar(32) NOT NULL DEFAULT '' COMMENT '非共有';
alter table lianjia_house change column community community varchar(32) NOT NULL DEFAULT '' COMMENT '小区名';
alter table lianjia_house change column district district varchar(64) NOT NULL DEFAULT '' COMMENT '城区';
alter table lianjia_house change column business_district business_district varchar(128) NOT NULL DEFAULT '' COMMENT '商圈';
alter table lianjia_house change column crawl_unit crawl_unit varchar(64) NOT NULL DEFAULT '' COMMENT '抓取相关';
alter table lianjia_house change column city city varchar(64) NOT NULL DEFAULT '' COMMENT '城市';

alter table trans_history change column id id varchar(32) NOT NULL COMMENT '';
alter table trans_history change column trans_price trans_price float NOT NULL DEFAULT 0 COMMENT '成交价格';
alter table trans_history change column trans_date trans_date date NOT NULL COMMENT '成交日期';
alter table trans_history change column list_price list_price float NOT NULL DEFAULT 0 COMMENT '挂牌价格';
alter table trans_history change column list_date list_date date NOT NULL DEFAULT '1970-01-01' COMMENT '挂牌日期';
alter table trans_history change column trans_age trans_age varchar(32) NOT NULL DEFAULT '' COMMENT '成交满几年';
alter table trans_history change column price_adjustment_times price_adjustment_times int(8) NOT NULL DEFAULT -1 COMMENT '调价次数';
alter table trans_history change column visit_times visit_times int(8) NOT NULL DEFAULT -1 COMMENT '带看次数';
alter table trans_history change column follow_times follow_times int(8) NOT NULL DEFAULT -1 COMMENT '关注次数';
alter table trans_history change column view_times view_times int(8) NOT NULL DEFAULT -1 COMMENT '浏览次数';

alter table second_hand_house_sale_info change column id id varchar(32) NOT NULL COMMENT '';
alter table second_hand_house_sale_info change column list_date list_date date NOT NULL DEFAULT '1970-01-01' COMMENT '挂牌日期';
alter table second_hand_house_sale_info change column last_trans_date last_trans_date date NOT NULL DEFAULT '1970-01-01' COMMENT '上次交易';
alter table second_hand_house_sale_info change column trans_age trans_age varchar(32) NOT NULL DEFAULT '' COMMENT '成交满几年';
alter table second_hand_house_sale_info change column mortgage mortgage  varchar(32) NOT NULL DEFAULT '' COMMENT '抵押信息';
alter table second_hand_house_sale_info change column certicate certicate varchar(32) NOT NULL DEFAULT '' COMMENT '房本备件';

alter table second_hand_house_price_info change column id id varchar(32) NOT NULL COMMENT '';
alter table second_hand_house_price_info change column list_price list_price float NOT NULL DEFAULT 0 COMMENT '挂牌价格';
alter table second_hand_house_price_info change column crawl_date crawl_date date NOT NULL DEFAULT '1970-01-01' COMMENT '价格抓取日期';
alter table second_hand_house_price_info change column visit_times visit_times int(8) NOT NULL DEFAULT -1 COMMENT '带看次数';
alter table second_hand_house_price_info change column follow_times follow_times int(8) NOT NULL DEFAULT -1 COMMENT '关注次数';
